/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Ejecutable;

/**
 *
 * @author Multi
 */
public class Confirmacion extends java.awt.Dialog {

    Boolean confirm = false;

    /**
     * Creates new form Confirmacion
     */
    public Confirmacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        bSi1 = new java.awt.Button();
        bNo1 = new java.awt.Button();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        tConfirm = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        bSi1.setLabel("Confirmar");
        bSi1.setPreferredSize(new java.awt.Dimension(170, 30));
        bSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSi1ActionPerformed(evt);
            }
        });
        panel1.add(bSi1);

        bNo1.setLabel("Denegar");
        bNo1.setPreferredSize(new java.awt.Dimension(170, 30));
        bNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNo1ActionPerformed(evt);
            }
        });
        panel1.add(bNo1);

        add(panel1, java.awt.BorderLayout.SOUTH);

        panel2.setLayout(new java.awt.GridLayout(1, 2));

        label2.setAlignment(java.awt.Label.RIGHT);
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setText("¿Estás seguro de que quieres ");
        panel2.add(label2);

        tConfirm.setText("PLACEHOLDER");
        panel2.add(tConfirm);

        add(panel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void bSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSi1ActionPerformed
        confirm = true;
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_bSi1ActionPerformed

    private void bNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNo1ActionPerformed
        confirm = false;
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_bNo1ActionPerformed

    public void setConfirm(String placeholder) {
        tConfirm.setText(placeholder);
    }

    public Boolean getSi() {
        return confirm;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Confirmacion dialog = new Confirmacion(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bNo1;
    private java.awt.Button bSi1;
    private java.awt.Label label2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Label tConfirm;
    // End of variables declaration//GEN-END:variables
}
