/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Ejecutable;

import java.util.ArrayList;

/**
 *
 * @author Multi
 */
public class VentanaExcepciones extends java.awt.Dialog {

    /**
     * Creates new form VentanaListados
     */
    public VentanaExcepciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void setContenido(String str){
        MensajeExcepcion.setText(str);
    }
    public void setCoordenadas(int x, int y){
        this.setLocation(x*108/100, y*125/100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBajoListadosExcepciones = new java.awt.Panel();
        SiSalir = new java.awt.Button();
        NoSalir = new java.awt.Button();
        MensajeExcepcion = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.BorderLayout(40, 40));

        SiSalir.setLabel("Sí");
        SiSalir.setPreferredSize(new java.awt.Dimension(170, 30));
        SiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiSalirActionPerformed(evt);
            }
        });
        PanelBajoListadosExcepciones.add(SiSalir);

        NoSalir.setLabel("No");
        NoSalir.setPreferredSize(new java.awt.Dimension(170, 30));
        NoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoSalirActionPerformed(evt);
            }
        });
        PanelBajoListadosExcepciones.add(NoSalir);

        add(PanelBajoListadosExcepciones, java.awt.BorderLayout.SOUTH);

        MensajeExcepcion.setText("label1");
        add(MensajeExcepcion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        // Hola
    }//GEN-LAST:event_closeDialog

    private void SiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SiSalirActionPerformed

    private void NoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoSalirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_NoSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaExcepciones dialog = new VentanaExcepciones(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label MensajeExcepcion;
    private java.awt.Button NoSalir;
    private java.awt.Panel PanelBajoListadosExcepciones;
    private java.awt.Button SiSalir;
    // End of variables declaration//GEN-END:variables
}
