/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Ejecutable;

/**
 *
 * @author Multi
 */
public class VentanaListados extends java.awt.Dialog {

    /**
     * Creates new form VentanaListados
     */
    public VentanaListados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setContenido(String str){
        Listador.setText(str);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBajoListados = new java.awt.Panel();
        DeAcuerdo = new java.awt.Button();
        Listador = new java.awt.TextArea();

        setTitle("Listado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new java.awt.BorderLayout(40, 40));

        DeAcuerdo.setLabel("De acuerdo");
        DeAcuerdo.setPreferredSize(new java.awt.Dimension(300, 30));
        DeAcuerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeAcuerdoActionPerformed(evt);
            }
        });
        PanelBajoListados.add(DeAcuerdo);

        add(PanelBajoListados, java.awt.BorderLayout.SOUTH);
        add(Listador, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void DeAcuerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeAcuerdoActionPerformed
        setVisible(false);
    }//GEN-LAST:event_DeAcuerdoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaListados dialog = new VentanaListados(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button DeAcuerdo;
    private java.awt.TextArea Listador;
    private java.awt.Panel PanelBajoListados;
    // End of variables declaration//GEN-END:variables
}
